### ISSUE TITLE
no registered plugin named 'napari-ome-zarr'

### ISSUE THREAD

**Issue by will-moore** [ome/napari-ome-zarr#86]
Reported at https://forum.image.sc/t/napari-napari-ome-zarr-plugin-is-not-registered/78482 and elsewhere...

I installed the `napari-ome-zarr` plugin either via pip installing or via the napari UI.
Then I specify the plugin on the command-line, trying to open a directory that *doesn't* contain an OME-Zarr.

Instead of a useful message, I get:
```
ValueError: There is no registered plugin named 'napari-ome-zarr'.
```

cc @DragaDoncila 

Full stack trace:
```
Traceback (most recent call last):
  File "/Users/wmoore/opt/anaconda3/envs/SSBD/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/Users/wmoore/opt/anaconda3/envs/ssbd/lib/python3.9/site-packages/napari/__main__.py", line 570, in main
    _run()
  File "/Users/wmoore/opt/anaconda3/envs/ssbd/lib/python3.9/site-packages/napari/__main__.py", line 344, in _run
    viewer._window._qt_viewer._qt_open(
  File "/Users/wmoore/opt/anaconda3/envs/ssbd/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 867, in _qt_open
    self.viewer.open(
  File "/Users/wmoore/opt/anaconda3/envs/ssbd/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1076, in open
    self._add_layers_with_plugins(
  File "/Users/wmoore/opt/anaconda3/envs/ssbd/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1276, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "/Users/wmoore/opt/anaconda3/envs/ssbd/lib/python3.9/site-packages/napari/plugins/io.py", line 105, in read_data_with_plugins
    raise ValueError(
ValueError: There is no registered plugin named 'napari-ome-zarr'.
Names of plugins offering readers are: set()
```

**Comment by DragaDoncila** [comment]
@will-moore yes I've seen this before and while I've never had a chance to track it down, I believe it is a bug in our file opening call stack. I will look into it and give you a clearer answer when I have one - hopefully end of this week.

Please don't hesitate to ping me again next week if you haven't heard from me 🙏

**Comment by DragaDoncila** [comment]
@will-moore just coming back to this, I tracked it down to another incarnation of what [napari #4026](https://github.com/napari/napari/pull/4026) was fixing. I've opened a PR in npe2 to address.

**Comment by psobolewskiPhD** [comment]
I believe this should be resolved via this set of PRs upstream:
https://github.com/napari/napari/pull/5698
https://github.com/napari/napari/pull/5739
https://github.com/napari/npe2/pull/276

**Comment by dstansby** [comment]
Since all those PRs are now merged, can we close this issue?
